### ISSUE TITLE
Interpreter-Datei für SWA Deutschlandtickets

### ISSUE THREAD

**Issue by T0tiToto** [sebastianknopf/uic-tlb-interpreter#6]
Zusammenfassung
Hi Sebastian, 
ich habe einen Interpreter für Deutschlandtickets der Stadtwerke Augsburg angelegt. Du kannst gerne einmal schauen ob die Datei so in Ordnung ist. Wenn alles passen sollte, dann kannst du den Interpreter gerne in deiner Sammlung aufnehmen. 
[SWA_DTicket_Interpreter.json](https://github.com/user-attachments/files/15815905/SWA_DTicket_Interpreter.json)

Falls noch was sein sollte, kannst du gerne Fragen.

Gruß Thomas

**Comment by sebastianknopf** [comment]
Sieht auf den ersten Blick einmal sehr gut aus, ich lade den am Wochenende mal noch auf mein Gerät zum testen. Hast Du mir ein Beispiel-Ticket dazu? Gerne per Mail an mail@sebastian-knopf.de, dann kann ich das gegenprüfen. Alternativ hast Du sicher schon im HGS und in der App getestet ... ?

**Comment by T0tiToto** [comment]
Ja, der Interpreter ist schon im Einsatz und sah soweit gut aus. Allerdings hatten wir nur ein Ticket zur Verfügung. Wir können also noch nicht ganz sagen, ob alles zu 100% funktioniert. Das Ticket schicke ich dir per Mail zu.

**Comment by sebastianknopf** [comment]
Ich habe den Interpreter entsprechend hinzugefügt. Beim Testen sind mir zwei Sachen aufgefallen: Die Tickets haben allesamt dieselbe IssuerPNR, d.h. wenn mehrere Tickets hintereinander von den SWA gescanned werden, wird möglicherweise angezeigt, dass das Ticket bereits kontrolliert wurde, falls Ihr das bei UIC auch prüft. Außerdem verwenden die einen interessanten Layout-Standard, der sich ja aber dank Interpreter problemlos abbilden lässt ;-)
